/* 1 */ package com.badlogic.gdx.graphics.g3d.particles.influencers;public abstract class ColorInfluencer extends Influencer { public ParallelArray.FloatChannel colorChannel; public void allocateChannels() { this.colorChannel = (ParallelArray.FloatChannel)this.controller.particles.addChannel(ParticleChannels.Color); } public static class Single extends ColorInfluencer { public ParallelArray.FloatChannel alphaInterpolationChannel; public ParallelArray.FloatChannel lifeChannel; public ScaledNumericValue alphaValue; public GradientColorValue colorValue; public void activateParticles(int param1Int1, int param1Int2) { int i; int j; for (param1Int2 = param1Int1 * (param1Int1 = ((ParallelArray.Channel)this.colorChannel).strideSize), i = param1Int1 * ((ParallelArray.Channel)this.alphaInterpolationChannel).strideSize, j = param1Int1 * ((ParallelArray.Channel)this.lifeChannel).strideSize + 2, param1Int1 = param1Int2 * param1Int1 + param1Int2; param1Int2 < param1Int1; ) { float f1 = this.alphaValue.newLowValue(), f2 = this.alphaValue.newHighValue() - f1; this.colorValue.getColor(0.0F, this.colorChannel.data, param1Int2); this.colorChannel.data[param1Int2 + 3] = oh.Zn(this.alphaValue, this.lifeChannel.data[j], f2, f1); ParallelArray.FloatChannel floatChannel;
/* 2 */         (floatChannel = this.alphaInterpolationChannel).data[i + 0] = f1; (floatChannel = this.alphaInterpolationChannel).data[i + 1] = f2; i = param1Int2 + ((ParallelArray.Channel)this.colorChannel).strideSize; int k = i + ((ParallelArray.Channel)floatChannel).strideSize; j += ((ParallelArray.Channel)this.lifeChannel).strideSize; k = i = k; }  } public Single() { GradientColorValue gradientColorValue; this(); this.colorValue = gradientColorValue; this(); this.alphaValue = scaledNumericValue; ScaledNumericValue scaledNumericValue; (scaledNumericValue = new ScaledNumericValue()).setHigh(1.0F); } public Single(Single param1Single) { this(); set(param1Single); } public void set(Single param1Single) { this.colorValue.load(param1Single.colorValue); this.alphaValue.load(param1Single.alphaValue); } public void allocateChannels() { super.allocateChannels(); ParallelArray.ChannelDescriptor channelDescriptor; (channelDescriptor = ParticleChannels.Interpolation).id = this.controller.particleChannels.newId(); this.alphaInterpolationChannel = (ParallelArray.FloatChannel)this.controller.particles.addChannel(channelDescriptor); this.lifeChannel = (ParallelArray.FloatChannel)this.controller.particles.addChannel(ParticleChannels.Life); } public void update() { byte b1; byte b2; byte b3; int i; for (b1 = 0, b2 = 0, b3 = 2, i = this.controller.particles.size * ((ParallelArray.Channel)this.colorChannel).strideSize + b1; b1 < i; ) { float f3 = this.lifeChannel.data[b3]; this.colorValue.getColor(f3, this.colorChannel.data, b1); float f1 = this.alphaInterpolationChannel.data[b2 + 0], f2 = this.alphaInterpolationChannel.data[b2 + 1]; this.colorChannel.data[b1 + 3] = oh.Zn(this.alphaValue, f3, f2, f1); int j = b1 + ((ParallelArray.Channel)this.colorChannel).strideSize, k = b2 + ((ParallelArray.Channel)this.alphaInterpolationChannel).strideSize, m = b3 + ((ParallelArray.Channel)this.lifeChannel).strideSize; }  } public Single copy() { return new Single(this); } public void write(It param1It) { param1It.Jv0(this.alphaValue, "alpha"); param1It.Jv0(this.colorValue, "color"); } public void read(It param1It, bM0 param1bM0) { this.alphaValue = (ScaledNumericValue)COm9.aD0(param1It, param1bM0, "alpha", ScaledNumericValue.class, null);
/* 3 */       bM0 bM01 = param1bM0.Jb("color");
/* 4 */       this.colorValue = (GradientColorValue)param1It.Uj0(GradientColorValue.class, null, this); } } public static class Random extends ColorInfluencer { public ParallelArray.FloatChannel colorChannel; public void allocateChannels() { this.colorChannel = (ParallelArray.FloatChannel)this.controller.particles.addChannel(ParticleChannels.Color); } public void activateParticles(int param1Int1, int param1Int2) { for (param1Int2 = param1Int1 * (param1Int1 = ((ParallelArray.Channel)this.colorChannel).strideSize), param1Int1 = param1Int2 * param1Int1 + param1Int2; param1Int2 < param1Int1; ) { this.colorChannel.data[param1Int2 + 0] = nx0.Mc0.nextFloat(); this.colorChannel.data[param1Int2 + 1] = nx0.Mc0.nextFloat(); this.colorChannel.data[param1Int2 + 2] = 
/* 5 */           nx0.Mc0.nextFloat();
/* 6 */         this.colorChannel.data[param1Int2 + 3] = 
/* 7 */           nx0.Mc0.nextFloat();
/* 8 */         param1Int2 += ((ParallelArray.Channel)this.colorChannel).strideSize; }
/*   */        }
/*   */ 
/*   */     
/*   */     public Random copy() {
/*   */       return new Random();
/*   */     } }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/com/badlogic/gdx/graphics/g3d/particles/influencers/ColorInfluencer.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */