/* 1 */ package f;public abstract class cg implements iq0 { public static final eo Qg = new eo(); public static final eo kW = new eo(); public byte z50; public Ih0 vn; public fo0 xo0; public K70 L7; public fQ lPt7 = new fQ(6); public int Tc = 0; public float TI0 = 0.0F; public int to0 = -1; public Yo0 Rt; public So Nk0; public So TC0; public lpt1[] yl0; public uT Jl; public cg(byte paramByte) { this.z50 = paramByte; xA(); LD0(UB0.M60.fG0(), UB0.M60.dL()); } public void xA() { this.vn = new Ih0(); (this.xo0 = new fo0()).Tz0(new qo(qo.iu0, 1.0F, 1.0F, 1.0F, 1.0F)); this(); Ql ql; fm fm; X3 x3; (new Ql()).xu = 32; this(ql); this(); this.L7 = new K70(x3, fm); km.u4.hB0 = ((paramBoolean, paramInt) -> { if (this.Tc == 4) return false;  if (!paramBoolean) return true;  if (h1.J20(paramInt, BM.Oq)) { if (this.Tc == 1 && this.Nk0 == null) ce0(this.to0 - 1);  } else if (h1.J20(paramInt, BM.M8)) { if (this.Tc == 1 && this.Nk0 == null) ce0(this.to0 + 1);  } else if (h1.J20(paramInt, BM.bC)) { int i; if ((i = this.Tc) == 1 && this.to0 > -1) { this.TI0 = 0.0F; this.Tc = 2; E4(); } else if (i == 2 && this.to0 > -1) { coM4(); }  } else if (h1.J20(paramInt, BM.lc) && this.Tc == 2) { yE(); }  return true; }); } public void yE() { this.TI0 = 99999.0F; this.Tc = 1; } public void E4() {} public int ce0(int paramInt) { if (paramInt < 0) { paramInt = 2; } else if (paramInt > 2) { paramInt %= 3; }  int i; if ((i = this.to0) == paramInt) return -2;  this.to0 = paramInt; if (i > -1) Kl(i);  (this.yl0[this.to0]).k = 1.0F; this.yl0[this.to0].rd(0, true, null); return i; } public abstract void coM4(); public void vm0() { this.TI0 = 0.0F; this.Tc = 3; } public void Kl(int paramInt) { this.yl0[paramInt].uq(); } public void Ti() { So so; if ((so = this.Nk0) != null && so.DD()) this.Nk0 = null;  this
/* 2 */       .TI0 = f; float f; if ((f = this.TI0 + UB0.M60.Qy) < 0.0F || f >= Float.MAX_VALUE) this.TI0 = 0.0F;  for (Hc0 hc0 = this.lPt7.r30(); hc0.hasNext(); ((lpt1)hc0.next()).wP(this.TI0)); } public void LD0(int paramInt1, int paramInt2) { this.vn.gV = paramInt1; this.vn.oA = paramInt2; this.vn.abstract(true); } public void og(boolean paramBoolean) { if (!paramBoolean) { int i = UB0.M60.fG0(); int j = UB0.M60.dL(); ou0.com8(0, 0, i, j); }  } public void lpt6() { fQ fQ1 = this.lPt7; this.L7.QJ0(fQ1, this.xo0); uT uT1; if ((uT1 = this.Jl) != null && this.to0 > -1) this.L7.q10(uT1, this.xo0);  } public void fu() {} public void Ye() { og(false); this.L7.mx0(this.vn); lpt6(); this.L7.end(); fu(); og(true); } public void dispose() { for (Hc0 hc0 = this.lPt7.r30(); hc0.hasNext(); ((lpt1)hc0.next()).Ea0()); this.Rt.dispose(); So so; if ((so = this.Nk0) != null) so.fr0 = true;  if ((so = this.TC0) != null) so
/* 3 */         .fr0 = true;  this
/* 4 */       .lPt7.clear(); this.L7.dispose(); }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/cg.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */