/* 1 */ package f;public final class Df { public final qa0 po0; public Un iV; public Un K8; public dQ cOM7; public dQ R; public final void ZA() { byte b; if ((b = this.po0.yw) == 2 || b == 3) { b = 1; } else { b = 0; }
/* 2 */      Un un = this.K8; if (this.lPt8 && b != 0) { b = 1; } else { b = 0; }  sk0(b); } public IN Go0; public vF0 XC0; public dQ ap; public Ip mK; public boolean lPt8 = true; public Df(ve paramve, qa0 paramqa0) { this.po0 = paramqa0; if (km.XU()) { vF0 vF01; this(72, 72); this.XC0 = new vF0(); vF01.ZH0().zT(128, 0); this.XC0.ZH0().tL(72, 72); } else { vF0 vF01; this(48, 48); this.XC0 = new vF0(); vF01.ZH0().zT(85, 0); this.XC0.ZH0().tL(48, 48); }  this.XC0.ZH0().qt(new U70[] { cC0.xK.PK0() }); this.XC0.ZH0().h(false); this.XC0.Xu("label-animation"); (this.ap = new dQ()).Xu("label-queue-positions"); (this.iV = new Un(paramqa0.P8())).Xu("label-tournament-name"); int i = paramqa0.jK0(); this.iV.tW(new ME(i)); this.cOM7 = new dQ(); this.Go0 = new IN(); (this.R = new dQ()).Xu("label-time-tournament"); (this.K8 = new Un(Ml0.OH0(5515))).Xu("buttondouble"); ZA(); this.K8.tW(new Bs0(paramve, paramqa0)); kc0(); } public final void kc0() { (this.mK = new Ip()).Xu("game-mode"); arrayOfU90[0] = this.mK.AUX(new JG0[] { this.iV }); arrayOfU90[1] = this.mK.AUX(new JG0[] { this.R }); arrayOfU90[2] = this.mK.AUX(new JG0[] { this.Go0 }); arrayOfU90[3] = this.mK.AUX(new JG0[] { this.XC0 }); arrayOfU90[4] = this.mK.AUX(new JG0[] { this.ap }); U90[] arrayOfU90; (arrayOfU90 = new U90[6])[5] = this.mK.AUX(new JG0[] { this.K8 }); this.mK.rK0(Mr.X60(this.mK, this.mK).cOM8(new U90[6]));
/*   */     
/* 4 */     arrayOfU90[0] = this.mK.vo0(new JG0[] { this.iV }); arrayOfU90[1] = this.mK.vo0(new JG0[] { this.R }); arrayOfU90[2] = this.mK.vo0(new JG0[] { this.Go0 }); arrayOfU90[3] = this.mK.vo0(new JG0[] { this.XC0 }); arrayOfU90[4] = this.mK.vo0(new JG0[] { this.ap }); (arrayOfU90 = new U90[6])[5] = this.mK.vo0(new JG0[] { this.K8 }); this.mK.WN(V2.Ur(this.mK, this.mK).cOM8(new U90[6])); }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/Df.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */