/* 1 */ package f;public class EC { public static boolean WD0 = false; public static String CB0 = ""; @mB0(key = "client.hotbar.item_id1", defaultValue = "0") public static short nF = 0; @mB0(key = "client.hotbar.item_id2", defaultValue = "0") public static short fr = 0; @mB0(key = "client.hotbar.item_id3", defaultValue = "0") public static short LS = 0; @mB0(key = "client.hotbar.item_id4", defaultValue = "0") public static short Qj = 0; @mB0(key = "client.hotbar.item_id5", defaultValue = "0") public static short Hc0 = 0; @mB0(key = "client.hotbar.item_id6", defaultValue = "0") public static short Y90 = 0; @mB0(key = "client.hotbar.item_id7", defaultValue = "0") public static short ef0 = 0; @mB0(key = "client.hotbar.item_id8", defaultValue = "0") public static short PU = 0; @mB0(key = "client.hotbar.item_id9", defaultValue = "0") public static short l4 = 0; @mB0(key = "client.hotbar.item_object_id1", defaultValue = "0") public static int xM = 0; public static void Qm(Xj0 paramXj0) { if (paramXj0 == null) { AUX = ""; WD0 = true; return; }  this(); StringBuilder stringBuilder; int[] arrayOfInt1; byte[] arrayOfByte; int arrayOfInt2[], i; for (arrayOfByte = paramXj0.JO, arrayOfInt1 = paramXj0.YB0, i = (arrayOfInt2 = paramXj0.R3).length; i-- > 0;) { if (arrayOfByte[i] == 1) { int j = arrayOfInt2[i], k = arrayOfInt1[i]; stringBuilder
/* 2 */           .append(Integer.toString(j)); stringBuilder.append(","); stringBuilder.append(Integer.toString(k)); stringBuilder.append(","); }  }
/* 3 */      AUX = stringBuilder.toString(); WD0 = true; } @mB0(key = "client.hotbar.item_object_id2", defaultValue = "0") public static int ie = 0; @mB0(key = "client.hotbar.item_object_id3", defaultValue = "0") public static int Fj = 0; @mB0(key = "client.hotbar.item_object_id4", defaultValue = "0") public static int Y60 = 0; @mB0(key = "client.hotbar.item_object_id5", defaultValue = "0") public static int yc = 0; @mB0(key = "client.hotbar.item_object_id6", defaultValue = "0") public static int FX = 0; @mB0(key = "client.hotbar.item_object_id7", defaultValue = "0") public static int NV = 0; @mB0(key = "client.hotbar.item_object_id8", defaultValue = "0") public static int w1 = 0; @mB0(key = "client.hotbar.item_object_id9", defaultValue = "0") public static int VA0 = 0; @mB0(key = "client.hotbar.auto_item_ids", defaultValue = "") public static String uA = ""; @mB0(key = "client.ui.matchmaking.battle_box_history", defaultValue = "") public static String AUX = ""; @mB0(key = "client.ui.matchmaking.game_mode_selection_history", defaultValue = "7,0,6,0,5,0,4,0,3,0,2,1,0,0") public static String x6 = ""; @mB0(key = "client.ui.matchmaking.languages", defaultValue = "") public static String Lm0 = ""; public static void ny0(Xj0 paramXj0) { if (paramXj0 == null) { x6 = ""; WD0 = true; return; }  this(); StringBuilder stringBuilder; int[] arrayOfInt1; byte[] arrayOfByte; int arrayOfInt2[], i; for (arrayOfByte = paramXj0.JO, arrayOfInt1 = paramXj0.YB0, i = (arrayOfInt2 = paramXj0.R3).length; i-- > 0;) { if (arrayOfByte[i] == 1) { int j = arrayOfInt2[i], k = arrayOfInt1[i]; stringBuilder.append(Integer.toString(j)); stringBuilder.append(","); stringBuilder.append(Integer.toString(k)); stringBuilder.append(","); }  }  x6 = stringBuilder.toString(); WD0 = true; } public static void fD0(String paramString) { if (WD0 && !CB0.isEmpty()) lpt2();  if (!paramString.matches("^[a-zA-Z0-9]*$")) paramString = "error";  CB0 = paramString = paramString.toLowerCase(); try { File file; Properties properties; FileInputStream fileInputStream; Bz.CN.mkdirs(); this(Bz.CN, paramString + ".properties"); if (!(new File()).exists()) file.createNewFile();  this(file); this(); (new Properties()).load(new InputStreamReader(fileInputStream)); (new FileInputStream()).close(); Properties[] arrayOfProperties; (arrayOfProperties = new Properties[1])[0] = properties; K.GP(EC.class, null, arrayOfProperties); } catch (Exception exception)
/* 4 */     { Bz.Jr
/*   */         
/* 6 */         .error(A9.lr0("FATAL"), De0.AT("Configuration for ", paramString, " not found or invalid."), exception); }
/*   */      }
/*   */ 
/*   */   
/*   */   public static void lpt2() {
/*   */     WD0 = false;
/*   */     if (CB0.isEmpty())
/*   */       return; 
/*   */     Cq.RG0((new File(Bz.CN, UQ.Vr0(new StringBuilder(), CB0, ".properties"))).getAbsolutePath(), EC.class);
/*   */   } }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/EC.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */