/* 1 */ package f;public class i { public final LPT3 BC; public final lj0 cZ; public final UD0 B70; public final Ud0 Lc0; public int ac0; public final short cq0; public int n30; public short iZ; public int SK0() { LPT3 lPT3; if ((lPT3 = this.BC) != null && this.ac0 < 1) return lPT3.ph0; 
/* 2 */     return this.ac0; } public final ArrayList wS; public final ArrayList Lq0; public i(LPT3 paramLPT3, Ud0 paramUd0, int paramInt1, short paramShort1, int paramInt2, short paramShort2) { ArrayList arrayList; this(); this.wS = this; this(); this.Lq0 = this; this.BC = paramLPT3; this.B70 = null; this.cZ = null; this.Lc0 = paramUd0; this.ac0 = paramInt1; this.cq0 = paramShort1; this.n30 = paramInt2; this.iZ = paramShort2; } public i(UD0 paramUD0, Ud0 paramUd0, int paramInt1, int paramInt2) { ArrayList arrayList; this(); this.wS = this; this(); this.Lq0 = this; this.BC = null; this.B70 = paramUD0; this.cZ = null; this.Lc0 = paramUd0; this.ac0 = paramInt1; this.cq0 = 1; this.n30 = paramInt2; this.iZ = Short.MAX_VALUE; } public i(lj0 paramlj0, Ud0 paramUd0, short paramShort1, int paramInt, short paramShort2) { ArrayList arrayList; this(); this.wS = this; this(); this.Lq0 = this; this.BC = null; this.B70 = null; this.cZ = paramlj0; this.Lc0 = paramUd0; this.ac0 = 0; this.cq0 = paramShort1; this.n30 = paramInt; this.iZ = paramShort2; } public final LPT3 Nm0() { return this.BC; } public final UD0 uf() { return this.B70; } public final lj0 jz0() { return this.cZ; } public final short zn() { return this.cq0; } public short WM() { LPT3 lPT3; if ((lPT3 = this.BC) != null) { short s2; short s3; if ((s3 = this.iZ) < (s2 = lPT3.ID0)) return s3;  short s1; if ((s1 = this.cq0) > 0)
/* 3 */         return (short)(s2 / s1);  return s2; }  return 1; } public int Vy0() { throw new RuntimeException("Not supported"); } public final int Dw() { return this.n30; } public final void ej0(int paramInt) { this.n30 = paramInt; } public final short iq0() { LPT3 lPT3; if ((lPT3 = this.BC) != null) return lPT3.bj0;  UD0 uD0; if ((uD0 = this.B70) != null) return uD0.AP;  lj0 lj01;
/* 4 */     if ((lj01 = this.cZ) != null)
/* 5 */       return this.Pu0;  return 0; } public final List yb() { return this.wS; }
/*   */   public final String WQ() { LPT3 lPT3; if ((lPT3 = this.BC) != null) { if (lPT3.vx() || km.Nr())
/* 7 */         return Ml0.OH0(this.BC.Iu);  this(); StringBuilder stringBuilder; (stringBuilder = new StringBuilder()).append(Ml0.OH0(this.BC.Iu)); if (!this.BC.vx()) { stringBuilder.append(" (").append(Ml0.OH0(1425)).append(")"); } else if (this.BC.IK0) { stringBuilder.append(" (").append(Ml0.OH0(1447)).append(")"); }  return stringBuilder.toString(); }
/* 8 */      lj0 lj01; return ((lj01 = this.cZ) != null) ? s60() : ""; } public final String H0() { LPT3 lPT3; if ((lPT3 = this.BC) != null) { StringBuilder stringBuilder; if (lPT3.vx() || km.XU()) return this.BC.Ey0(38);  this(); if (!this.BC.vx()) { stringBuilder.append(Ml0.OH0(1425)); stringBuilder.append("\n"); } else if (this.BC.IK0) { stringBuilder.append(Ml0.OH0(1448)); stringBuilder.append("\n"); }  if (stringBuilder.length() > 0) stringBuilder.append("\n");  stringBuilder.append(this.BC.Ey0(38)); return stringBuilder.toString(); }  lj0 lj01; if ((lj01 = this.cZ) != null) { String str; if (!this.vh) { str = Ml0.OH0(1451); } else { str = Ml0.OH0(((lj0)this).Pu0 + 295000); }  return this; }  return ""; }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/i.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */