/* 1 */ package f;public final class Kn implements cw0 { public final Xb0 jw0; public IntBuffer FM; public int c90; public int Uj; public int R2; public boolean g60; public final void gk0(int paramInt, short[] paramArrayOfshort) { int j = 0; byte[] arrayOfByte2; if ((arrayOfByte2 = this.Pl0) == null || arrayOfByte2.length < paramInt * 2) this.Pl0 = new byte[paramInt * 2];  int k, m; for (k = Math.min(j + paramInt, paramArrayOfshort.length), m = 0; j < k; ) { short s = paramArrayOfshort[j]; m++; this.Pl0[m] = (byte)(s & 0xFF); int n = m + 1; this.Pl0[m] = (byte)(s >> 8 & 0xFF); j++; m = n; }  byte[] arrayOfByte1 = this.Pl0; int i = 0; if ((j = paramInt * 2) >= 0) { if (this.c90 == -1) { if ((this.c90 = this.jw0.VH(true)) == -1) return;  if (this.FM == null) { this.FM = BufferUtils.createIntBuffer(this.ie0); AL10.alGetError(); AL10.alGenBuffers(this.FM); if (AL10.alGetError() != 0) throw new JU("Unabe to allocate audio buffers.");  }  AL10.alSourcei(this.c90, 4103, 0); AL10.alSourcef(this.c90, 4106, this.Nb); for (k = 0; k < this.ie0; ) { j = Math.min(this.Qx0, j); this.K0.clear(); this.K0.put(arrayOfByte1, i, j).flip(); i = this.Uj; ByteBuffer byteBuffer = this.K0; int n = this.R2; AL10.alBufferData(m = this.FM.get(k), i, byteBuffer, n); AL10.alSourceQueueBuffers(this.c90, m); i = j - j; j = i + j; k++; i = j = i; }  AL10.alSourcePlay(this.c90); this.g60 = true; }  label50: while (j > 0)
/* 2 */       { k = Math.min(this.Qx0, j); while (true) { float f; if (AL10.alGetSourcei(this.c90, 4118) <= 0 || (m = AL10.alSourceUnqueueBuffers(this.c90)) == 40963) { f = 1000.0F; try { Thread.sleep((long)(this.vK0 * f)); } catch (InterruptedException interruptedException) {} continue; }  this.K0.clear(); this.K0.put(arrayOfByte1, i, k).flip(); int n = this.Uj; ByteBuffer byteBuffer = this.K0; int i1 = this.R2; AL10.alBufferData(f, n, byteBuffer, i1); AL10.alSourceQueueBuffers(this.c90, f); if (!this.g60 || AL10.alGetSourcei(this.c90, 4112) != 4114) { AL10.alSourcePlay(this.c90); this.g60 = true; }  j -= k; i += k; continue label50; }  }  return; }
/* 3 */      throw new IllegalArgumentException("length cannot be < 0."); } public float Nb; public float vK0; public byte[] Pl0; public final int Qx0; public final int ie0; public final ByteBuffer K0; public Kn(Xb0 paramXb0, int paramInt1, boolean paramBoolean, int paramInt2, int paramInt3) { byte b; char c; this.c90 = -1; this.Nb = 1.0F; this.jw0 = paramXb0; if (paramBoolean) { b = 1; } else { b = 2; }  this.Qx0 = paramInt2; this.ie0 = paramInt3; if (b > 1) { c = 'ᄃ'; } else { c = 'ᄁ'; }  this.Uj = c; this.R2 = paramInt1; this.vK0 = paramInt2 / 2.0F / b / paramInt1; this.K0 = BufferUtils.createByteBuffer(paramInt2); } public final void dispose() { if (this.FM == null) return;  int i; if ((i = this.c90) != -1) { Xb0 xb0; if (!(xb0 = this.jw0).jj0) { AL10.alSourceStop(i); AL10.alSourcei(i, 4105, 0); Long long_; if ((long_ = (Long)xb0.lpT8.remove(i)) != null) xb0.vI0.sH(long_.longValue());  xb0.a10.oU(i); }  this.c90 = -1; }  AL10.alDeleteBuffers(this.FM); this.FM = null; }
/*   */ 
/*   */   
/*   */   public final void oC0() {}
/*   */   
/*   */   public final void resume() {} }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/Kn.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */