/* 1 */ package f;public class n90 extends wj0 implements mX, P80 { public final nK pj; public final pRn BE; public Ui0 iq0; public void W8(fB0 paramfB0, int paramInt1, int paramInt2, int paramInt3, int paramInt4) { this.pj.Dk0.yT
/* 2 */       .og0(tw.kI0);
/* 3 */     this.iq0.vr(this.pj.Dk0.we(this.BE)); float f1 = paramInt1, f2 = paramInt2, f3 = paramInt3, f4 = paramInt4; this.iq0.t50(f1, f2, f3, f4); this.iq0.Ne(this.pj.Dk0.yT); } public n90(nK paramnK, int paramInt1, int paramInt2, int paramInt3, int paramInt4, pRn parampRn) { super(paramInt1, paramInt2, paramInt3, paramInt4); int j; this.pj = paramnK; if (parampRn == null) parampRn = pRn.WHITE;  this.BE = parampRn; Ui0 ui0 = new Ui0(); Texture texture = paramnK.pd0; if (paramInt3 > 0) { j = 0; } else { j = paramInt3 * -1; }  paramInt1 += j; if (paramInt4 > 0) { j = 0; } else { j = paramInt4 * -1; }  int i = paramInt2 + j; this(texture, paramInt1, i, paramInt3, paramInt4); this.iq0 = ui0; ui0.zt0(false, true); } public n90(n90 paramn90, pRn parampRn) { super(paramn90); int i1; this.pj = nK1; this.BE = parampRn; Ui0 ui0 = new Ui0(); nK nK1; Texture texture = (nK1 = paramn90.pj).pd0; int j = this.Pe; int k; if ((k = this.sl) > 0) { m = 0; } else { m = k * -1; }  j += m; int m = this.Ub0; int n; if ((n = this.N5) > 0) { i1 = 0; } else { i1 = n * -1; }  int i = m + i1; this(texture, j, i, k, n); this.iq0 = ui0; ui0.zt0(false, true); } public final void Gt0(uP paramuP, int paramInt1, int paramInt2) { int i = this.sl; int j = this.N5; W8(paramuP, paramInt1, paramInt2, i, j); } public final void O2(fB0 paramfB0, int paramInt1, int paramInt2, int paramInt3, int paramInt4, int paramInt5, int paramInt6) { this.pj.Dk0.yT.og0(tw.kI0); this.iq0.vr(this.pj.Dk0.we(this.BE)); int i, j; if (paramInt5 * (i = this.sl) != paramInt3 || paramInt6 * (j = this.N5) != paramInt4)
/* 4 */     { while (paramInt6 > 0)
/* 5 */       { int k; for (i = paramInt4 / paramInt6, j = 0, k = 0; k < paramInt5; ) { int m = ++k * paramInt3 / paramInt5; float f1 = (paramInt1 + j), f2 = paramInt2, f3 = (m - j), f4 = i; this.iq0.t50(f1, f2, f3, f4); this.iq0.Ne(this.pj.Dk0.yT); j = m; }  paramInt2 += i; paramInt4 -= i; paramInt6--; }  return; }  while (paramInt6-- > 0) { for (paramInt4 = paramInt1, paramInt3 = paramInt5; paramInt3-- > 0; ) { float f1 = paramInt4, f2 = paramInt2, f3 = i, f4 = j; this.iq0.t50(f1, f2, f3, f4); this.iq0.Ne(this.pj.Dk0.yT); int k = paramInt4 + i; }  paramInt2 += j; }  } public mX rv0(pRn parampRn) { if (parampRn != null) return (parampRn = this.BE.o10(parampRn)).equals(this.BE) ? this : new n90(this, parampRn);  throw new NullPointerException("color == null"); } public final pe0 LPT8() { Texture texture = this.iq0.G3; float f1 = this.iq0.mP; float f2 = this.iq0.WT; float f3 = this.iq0.zV; float f4 = this.iq0.bh0; return new pe0(this, f1, f2, f3, f4); }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/n90.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */