/* 1 */ package f;public abstract class nc0 { static { boolean bool; byte b; short s; char c; int i; long l; float f; double d; if (System.getProperty("gnu.trove.verbose", null) != null) { bool = true; } else { bool = false; }  String str7 = System.getProperty("gnu.trove.no_entry.byte", "0"); if ("MAX_VALUE".equalsIgnoreCase(str7)) { b = Byte.MAX_VALUE; } else if ("MIN_VALUE".equalsIgnoreCase(b)) { b = -128; } else { b = Byte.valueOf(b).byteValue(); }  if (b > Byte.MAX_VALUE) { b = Byte.MAX_VALUE; } else if (b < -128) { b = -128; }  il = b; if (bool) System.out.println("DEFAULT_BYTE_NO_ENTRY_VALUE: " + b);  String str6 = System.getProperty("gnu.trove.no_entry.short", "0"); if ("MAX_VALUE".equalsIgnoreCase(str6)) { s = Short.MAX_VALUE; } else if ("MIN_VALUE".equalsIgnoreCase(s)) { s = -32768; } else { s = Short.valueOf(s).shortValue(); }  if (s > Short.MAX_VALUE) { s = Short.MAX_VALUE; } else if (s < -32768) { s = -32768; }  O00 = s; if (bool) System.out.println("DEFAULT_SHORT_NO_ENTRY_VALUE: " + s);  String str5 = System.getProperty("gnu.trove.no_entry.char", "\000"); if ("MAX_VALUE".equalsIgnoreCase(str5)) { c = '￿'; } else if ("MIN_VALUE".equalsIgnoreCase(c)) { c = Character.MIN_VALUE; } else { c = c.toCharArray()[0]; }  if (c > '￿') { c = '￿'; } else if (c < '\000') { c = Character.MIN_VALUE; }  if (bool) System.out
/* 2 */         .println(B40.df("DEFAULT_CHAR_NO_ENTRY_VALUE: ").append(Integer.valueOf(c)).toString());  String str4 = System.getProperty("gnu.trove.no_entry.int", "0"); if ("MAX_VALUE".equalsIgnoreCase(str4)) { i = Integer.MAX_VALUE; } else if ("MIN_VALUE".equalsIgnoreCase(i)) { i = Integer.MIN_VALUE; } else { i = Integer.valueOf(i).intValue(); }  pz0 = i; if (bool) System.out.println("DEFAULT_INT_NO_ENTRY_VALUE: " + i);  String str3 = System.getProperty("gnu.trove.no_entry.long", "0"); if ("MAX_VALUE".equalsIgnoreCase(str3)) { l = Long.MAX_VALUE; } else if ("MIN_VALUE".equalsIgnoreCase(l)) { l = Long.MIN_VALUE; } else { l = Long.valueOf(l).longValue(); }  Zx0 = l; if (bool) System.out.println("DEFAULT_LONG_NO_ENTRY_VALUE: " + l);  String str2 = System.getProperty("gnu.trove.no_entry.float", "0"); if ("MAX_VALUE".equalsIgnoreCase(str2)) { f = Float.MAX_VALUE; } else if ("MIN_VALUE".equalsIgnoreCase(f)) { f = Float.MIN_VALUE; } else if ("MIN_NORMAL".equalsIgnoreCase(f)) { f = 1.17549435E-38F; } else if ("NEGATIVE_INFINITY".equalsIgnoreCase(f)) { f = Float.NEGATIVE_INFINITY; } else if ("POSITIVE_INFINITY".equalsIgnoreCase(f)) { f = Float.POSITIVE_INFINITY; } else { f = Float.valueOf(f).floatValue(); }  if (bool) System.out.println("DEFAULT_FLOAT_NO_ENTRY_VALUE: " + f);  String str1 = System.getProperty("gnu.trove.no_entry.double", "0"); if ("MAX_VALUE".equalsIgnoreCase(str1)) { d = Double.MAX_VALUE; } else if ("MIN_VALUE".equalsIgnoreCase(d)) { d = Double.MIN_VALUE; } else if ("MIN_NORMAL".equalsIgnoreCase(d)) { d = 2.2250738585072014E-308D; } else if ("NEGATIVE_INFINITY".equalsIgnoreCase(d)) { d = Double.NEGATIVE_INFINITY; } else if ("POSITIVE_INFINITY".equalsIgnoreCase(d)) { d = Double.POSITIVE_INFINITY; } else { d = Double.valueOf(d).doubleValue(); }  Pd0 = d; if (bool) System.out.println("DEFAULT_DOUBLE_NO_ENTRY_VALUE: " + d);  }
/*   */ 
/*   */   
/*   */   public static final byte il;
/*   */   public static final short O00;
/*   */   public static final int pz0;
/*   */   public static final long Zx0;
/*   */   public static final double Pd0; }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/nc0.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       1.1.3
 */