/* 1 */ package f;public final class qh0 extends k7 { public static boolean ak() { String str; boolean bool = TinyFileDialogs.tinyfd_messageBox("tinyfd_query", null, "ok", "info", false); if (q00.Sk && bool) { if ((str = TinyFileDialogs.tinyfd_getGlobalChar("tinyfd_response")) == null) return false;  byte b = -1; switch (str.hashCode()) { case 107360630: if (!str.equals("qarma")) break;  b = 6; break;case 119388: if (!str.equals("yad")) break;  b = 5; break;case -397325720: if (!str.equals("zenity3")) break;  b = 4; break;case -705553621: if (!str.equals("zenity")) break;  b = 3; break;case -745020811: if (!str.equals("shellementary")) break;  b = 2; break;case -760550259: if (!str.equals("matedialog")) break;  b = 1; break;case -858472077: if (!str.equals("kdialog")) break;  b = 0; break; }  switch (b) { default: return false;case 0: case 1: case 2: case 3: case 4: case 5: case 6: break; }  return true; }  return str; } public final void iJ0(String paramString1, String paramString2, LP paramLP, Runnable paramRunnable, boolean paramBoolean) { String str2, str1 = paramString1.replace('"', ' '); str1 = replace('\'', ' '); paramString1 = paramString2.replace('"', ' ').replace('\'', ' '); int i; if ((i = paramLP.ordinal()) != 0) { if (i != 2) { if (i != 3) { str2 = "info"; } else { str2 = "question"; }  } else { str2 = "warning"; }  } else { str2 = "error"; }
/* 2 */      TinyFileDialogs.tinyfd_messageBox(this, paramString1, "info", str2, true); if (paramRunnable != null) { Q50 q50; if (paramBoolean || (q50 = UB0.Kg0) == null) { paramRunnable.run(); return; }  fN(paramRunnable); }  } public static void Nz() { try { System.out.println("tinyfd_version " + TinyFileDialogs.tinyfd_getGlobalChar("tinyfd_version")); PrintStream printStream = System.out; boolean bool; if (bool = ak()) {  } else {  }  String str = "Console"; printStream.println("tinyfd_response " + str + " " + TinyFileDialogs.tinyfd_getGlobalChar("tinyfd_response")); if (bool) { km.f70 = new qh0(); } else { throw new RuntimeException("TinyFD GUI unavailable"); }  } catch (Exception exception) { uK0.BH0(); } catch (Error error) {} } public final void lpt3(String paramString1, String paramString2, LP paramLP, Runnable paramRunnable1, Runnable paramRunnable2, boolean paramBoolean) { String str2, str1 = paramString1.replace('"', ' '); str1 = replace('\'', ' '); paramString1 = paramString2.replace('"', ' ').replace('\'', ' '); int i; if ((i = paramLP.ordinal()) != 0) { if (i != 2) { if (i != 3) { str2 = "info"; } else { str2 = "question"; }  } else { str2 = "warning"; }  } else { str2 = "error"; }  if (TinyFileDialogs.tinyfd_messageBox(this, paramString1, "yesno", str2, true)) { if (paramRunnable1 != null) { Q50 q50; if (paramBoolean || (q50 = UB0.Kg0) == null) { paramRunnable1.run(); return; }  fN(paramRunnable1); }  } else if (paramRunnable2 != null) { Q50 q50; if (paramBoolean || (q50 = UB0.Kg0) == null) { paramRunnable2.run(); return; }  fN(paramRunnable2); }
/*   */      }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/qh0.class
 * Java compiler version: 17 (61.0)
 * JD-Core Version:       1.1.3
 */