/* 1 */ package f;public final class UD0 { public static final short[] uc0 = new short[0]; public short AP; public int gn0; public int my0 = 0; public int dv0 = 0; public int UH0 = 0; public int qA0 = 0; public int j90 = 0; public int ha0 = 0; public Ht0 FH; public Ht0 e6; public int kn; public short[] qV; public short[] Ny; public int FD; public Es eb; public Ls0 I30; public Ls0 LPt6; public final short[] Po; public short TL; public final boolean ct() { byte b = 2; if (this.Po[b] > 0) { b = 1; } else { b = 0; }  return b; } public short Q5; public byte Uf; public UD0 h3; public UD0 es; public byte D3; public short jt; public short L90; public short fu; public List hz0; public ArrayList WI; public short[] G1; public boolean lS; public boolean hL; public byte[] HL0; public DO ee; public HashSet G2; public short[][] Pw0; public UD0 FW; public UD0(short paramShort) { Ht0 ht0 = Ht0.Ku; this.e6 = this; this.kn = 0; this.Ny = uc0; this.FD = 0; this.eb = Es.sF; Ls0 ls0 = Ls0.yi; this.LPt6 = this; this.Po = new short[3]; this.h3 = null; this.es = null; this.D3 = -1; this.jt = 0; this.L90 = 0; this.fu = 0; this.hz0 = new ArrayList(); this.WI = new ArrayList(); this.G1 = new short[6]; this.lS = false; this.hL = false; this.HL0 = new byte[6]; this.ee = DO.U7; this.G2 = new HashSet(); this.Pw0 = new short[KM.xH.length][0]; this.FW = null; this.AP = paramShort; this.gn0 = paramShort + 150000; this.G1[this.G1.length - 1] = paramShort; } public final short zq0(int paramInt) { short[] arrayOfShort; return (paramInt < 0 || paramInt > 2) ? 0 : ((paramInt == 1 && (arrayOfShort = this.Po)[paramInt] < 1) ? arrayOfShort[0] : this.Po[paramInt]); } public final short[] S60() { return this.Po; } public final short Uf() { return this.AP; } public final String wp() { return o60(false); } public final String o60(boolean paramBoolean) { if (this.AP == 0) return "???";  UD0 uD0; if (!paramBoolean && (uD0 = this.h3) != null) return uD0.o60(false); 
/* 2 */     return Ml0.OH0(this.gn0); } public final short eD0() { return PP((byte)-1); } public final short PP(byte paramByte) { short[] arrayOfShort; return (paramByte < 0 || paramByte >= (arrayOfShort = this.G1).length) ? this.G1[this.G1.length - 1] : arrayOfShort[paramByte]; } public final Ht0 Sl0(byte paramByte) { return (this.AP == 493 && paramByte > 0) ? Ht0.wY(paramByte) : this.FH; } public final Ht0 pf0(byte paramByte) { return (this.AP == 493 && paramByte > 0) ? Ht0.wY(paramByte) : this.e6; } public final Es uc() { return this.eb; } public final int qC(hR paramhR) { switch (paramhR.ordinal()) { default: return 0;case 5: return this.ha0;case 4: return this.j90;case 3: return this.qA0;case 2: return this.UH0;case 1: return this.dv0;case 0: break; }  return this.my0; } public final byte Tb() { return this.Uf; } public final UD0 Qo0() { UD0 uD0; return ((uD0 = this.h3) != null) ? uD0 : this; } public final boolean HH0(KM paramKM, short paramShort) { short[] arrayOfShort; int i; byte b; for (i = (arrayOfShort = this.Pw0[paramKM.vp]).length, b = 0; b < i; ) { if (this[b] == paramShort) return true;  b++; }  return false; } public final UD0 T8() { return this.FW; } public final UD0 Fk0() { UD0 uD0; return ((uD0 = this.es) == null) ? this : uD0; } public final boolean Tf(byte paramByte) { int i; if ((i = this.FD) != 0) { if (i != 254) { if (i != 255) if (paramByte == 0 || paramByte == 1) return true;   return (paramByte == -1); }  return (paramByte == 1); }  return (paramByte == 0); } public final boolean W40(byte paramByte, short paramShort) { for (Iterator<oC0> iterator = this.hz0.iterator(); iterator.hasNext();) { if ((oC0 = iterator.next()).ly0 == paramShort && oC0.pE <= paramByte) return true;  }
/* 3 */      KM[] arrayOfKM; int i; byte b; for (i = (arrayOfKM = KM.xH).length, b = 0; b < i; ) { if (HH0(arrayOfKM[b], paramShort)) return true;  b++; }  this(); ArrayList<UD0> arrayList; while ((this = this.FW) != null && !arrayList.contains(this)) { if (W40(paramByte, paramShort)) return true;  arrayList.add(this); }  return false; }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/UD0.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */