/* 1 */ package f;public abstract class VN { public static uE0 Ny0(xS paramxS, String paramString) { if ((paramString = paramxS.S3(paramString)) == null) return null;  try { int i; uE0 uE0; int[] arrayOfInt; int j; if ((j = (arrayOfInt = gd0.dB0(paramString)).length) != 1) { if (j != 2) { if (j == 4) { i = arrayOfInt[0]; int k = arrayOfInt[1], m = arrayOfInt[2], n = arrayOfInt[3]; this(i, k, m, n); } else { throw paramxS.s70("Unsupported border format"); }  } else { i = i[0]; this(i, i[1]); }  } else { this(i[0]); }  return uE0; } catch (NumberFormatException numberFormatException) { throw paramxS.q70("Unable to parse border size", numberFormatException); }  } public static void n8(xS paramxS, String paramString) { if (paramString != null) { if (paramString.length() != 0) { if (!"none".equals(paramString)) { if (paramString.indexOf('*') < 0) { if (paramString.indexOf('/') < 0) return;  throw paramxS.s70("'/' is not allowed in names"); }  throw paramxS.s70("'*' is not allowed in names"); }  throw paramxS.s70("can't use reserved name \"none\""); }  throw paramxS.s70("empty name not allowed"); }  throw paramxS
/*   */ 
/*   */       
/* 4 */       .s70(B40.df("missing 'name' on '").append(paramxS.bb.getName()).append("'").toString()); } public static pRn qs(xS paramxS, String paramString, q80 paramq80) { try { pRn pRn; if ((pRn = pRn.p7(paramString)) == null && paramq80 != null) pRn = (pRn)paramq80.Yz0(paramString, false, pRn.class, null);  if (pRn != null) return pRn;  throw paramxS.s70("Unknown color name: " + paramString); } catch (NumberFormatException numberFormatException) { throw paramxS.q70("unable to parse color code", numberFormatException); }  } public static Map W9(TreeMap paramTreeMap, String paramString1, String paramString2, JB paramJB) { int j; if ((j = paramString2.length()) > 0 && paramString2.charAt(j - 1) != '.') paramString2 = paramString2.concat(".");  int i = paramString1.length() - 1; SortedMap<?, ?> sortedMap; if ((sortedMap = paramTreeMap.subMap(paramString1.substring(0, i), (paramString1 = paramString1.substring(0, i)).concat("￿"))).isEmpty()) return sortedMap;  this(); HashMap<Object, Object> hashMap; for (Iterator<Map.Entry> iterator = sortedMap.entrySet().iterator(); iterator.hasNext(); ) { Map.Entry<String, ?> entry; String str = (entry = iterator.next()).getKey(); if (Jd0 || str.startsWith(paramString1)) { if ((entry = (Map.Entry<String, ?>)entry.getValue()) == paramJB) entry = null;  hashMap.put(paramString2.concat(str.substring(i)), entry); continue; }  throw new AssertionError(); }  return hashMap; } public static Nm0 A10(xS paramxS) { boolean bool; String str; if ((str = paramxS.S3("if")) == null) { bool = true; } else { bool = false; }  if (str == null) str = paramxS.S3("unless");  if (str != null) try { boolean bool1; ru0 ru0; this(str); Nm0 nm0 = Nm0.DQ(new ru0()); if ((new ru0()).Qq < str.length()) { bool1 = true; } else { bool1 = false; }  if (!bool1) { nm0.vS ^= bool; return nm0; }  ru0.ds(); throw null; } catch (ParseException parseException) { throw paramxS.q70("Unable to parse condition", parseException); }   return null; }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/VN.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */