/* 1 */ package f;public final class vw implements iq0 { public final re0 n3; public final Matrix4 Wb0; public fQ Bs; public final Rm0 W60; public Dd0 VK; public vw(int paramInt, Rm0 paramRm0, boolean paramBoolean) { this.Wb0 = new Matrix4(); this.Bs = new fQ(); this.qH0 = new fQ(8); this.Rf = new o0(8); this.W60 = paramRm0; if (!paramBoolean || paramInt <= 8191)
/* 2 */     { short s; lw0 lw0; re0 re01 = new re0(); byte b = 1; if (paramBoolean) { i = 4; } else { i = 6; }  int i = paramInt * i; if (paramBoolean) { s = paramInt * 6; } else { s = 0; }  this(1, 2, "a_position"); lw0[] arrayOfLw0; (arrayOfLw0 = new lw0[3])[0] = lw0; this(4, 4, "a_color"); (new lw0[3])[1] = lw0; this(16, 2, "a_texCoord0"); (new lw0[3])[2] = lw0; this(b, i, s, arrayOfLw0); this.n3 = re01; re01.wJ0(); if (paramBoolean) { short[] arrayOfShort; short s1; for (arrayOfShort = new short[paramInt *= 6], s1 = 0, b = 0; b < paramInt; ) { arrayOfShort[b + 0] = s1; i = b + 1; arrayOfShort[i] = (short)(s1 + 1); i = b + 2; s = (short)(s1 + 2); arrayOfShort[i] = s; arrayOfShort[b + 3] = s; i = b + 4; arrayOfShort[i] = (short)(s1 + 3); arrayOfShort[b + 5] = s1; b += 6; s1 = (short)(s1 + 4); }  this.n3.cOM9(arrayOfShort); }  this.Wb0.ZA0(UB0.M60.fG0(), UB0.M60.dL()); return; }  throw new IllegalArgumentException(XD0.SD0("Can't have more than 8191 sprites per batch: ", paramInt)); } public final fQ qH0; public final o0 Rf; public final void dispose() { this.n3.dispose(); Rm0 rm0; if ((rm0 = this.W60) != null) dispose();  } public vw() { this(1000, false); } public vw(int paramInt, boolean paramBoolean) { this(paramInt, sw(), paramBoolean); } public static Rm0 sw() { this("attribute vec4 a_position;\nattribute vec4 a_color;\nattribute vec2 a_texCoord0;\nuniform mat4 u_projectionViewMatrix;\nvarying vec4 v_color;\nvarying vec2 v_texCoords;\n\nvoid main()\n{\n   v_color = a_color;\n   v_color.a = v_color.a * (255.0/254.0);\n   v_texCoords = a_texCoord0;\n   gl_Position =  u_projectionViewMatrix * a_position;\n}\n", "#ifdef GL_ES\nprecision mediump float;\n#endif\nvarying vec4 v_color;\nvarying vec2 v_texCoords;\nuniform sampler2D u_texture;\nvoid main()\n{\n  gl_FragColor = v_color * texture2D(u_texture, v_texCoords);\n}"); Rm0 rm0; if ((new Rm0()).Xu0) return rm0;  throw new IllegalArgumentException(
/* 3 */         B40.df("Error compiling shader: ")
/* 4 */         .append(rm0.ET()).toString()); }
/*   */    }


/* Location:              /Users/vnnsnnt/Documents/Codespace/JavaWorkspace/RedTrainer/src/main/java/org/trainer/client/PokeMMO.jar!/f/vw.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */